; PlatformIO Project Configuration File

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

monitor_speed = 115200
upload_protocol = esptool
upload_flags = 
    --before=no_reset
    --after=no_reset

board_build.partitions = partitions.csv
board_build.filesystem = littlefs

lib_deps =
    olkal/HX711_ADC@1.2.12
    fastled/FastLED@^3.9.0
    me-no-dev/ESPAsyncWebServer@^3.1.0
    bblanchon/ArduinoJson@^7.3.0
    ayushsharma82/ElegantOTA@^3.1.0

build_flags =
    -D FASTLED_RMT_MAX_CHANNELS=1
    -D FASTLED_RMT_BUILTIN_DRIVER=1
